amclist = [
    "quant Mutual Fund"
    "BNP Paribas Mutual Fund",
    "Shriram Mutual Fund",
    "BOI AXA Mutual Fund",
    "Aditya Birla Sun Life Mutual Fund",
    "IIFL Mutual Fund",
    "Union Mutual Fund",
    "SBI Mutual Fund",
    "Franklin Templeton Mutual Fund",
    "LIC Mutual Fund",
    "Canara Robeco Mutual Fund",
    "Taurus Mutual Fund",
    "IL&FS Mutual Fund (IDF)",
    "DSP Mutual Fund",
    "YES Mutual Fund",
    "PPFAS Mutual Fund",
    "Invesco Mutual Fund",
    "Trust Mutual Fund",
    "Quantum Mutual Fund",
    "IIFCL Mutual Fund (IDF)",
    "Mirae Asset Mutual Fund",
    "Nippon India Mutual Fund",
    "Sundaram Mutual Fund",
    "ITI Mutual Fund",
    "Axis Mutual Fund",
    "IDFC Mutual Fund",
    "Kotak Mahindra Mutual Fund",
    "IDBI Mutual Fund",
    "Motilal Oswal Mutual Fund",
    "HSBC Mutual Fund",
    "PGIM India Mutual Fund",
    "Edelweiss Mutual Fund",
    "UTI Mutual Fund",
    "HDFC Mutual Fund",
    "Indiabulls Mutual Fund",
    "ICICI Prudential Mutual Fund",
    "Tata Mutual Fund",
    "Navi Mutual Fund",
    "Principal Mutual Fund",
    "Baroda Mutual Fund",
    "Mahindra Manulife Mutual Fund",
    "L&T Mutual Fund",
    "JM Financial Mutual Fund"

]
